package com.buildstack.promptly.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFADC6FF)
val md_theme_dark_onPrimary = Color(0xFF002E69)
val md_theme_dark_primaryContainer = Color(0xFF4B8EFF)
val md_theme_dark_onPrimaryContainer = Color(0xFF00285C)
val md_theme_dark_secondary = Color(0xFFD3FBFF)
val md_theme_dark_onSecondary = Color(0xFF00363A)
val md_theme_dark_secondaryContainer = Color(0xFF00EEFC)
val md_theme_dark_onSecondaryContainer = Color(0xFF00686F)
val md_theme_dark_tertiary = Color(0xFFC8C6C5)
val md_theme_dark_onTertiary = Color(0xFF313030)
val md_theme_dark_tertiaryContainer = Color(0xFF929090)
val md_theme_dark_onTertiaryContainer = Color(0xFF2A2A2A)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF121414)
val md_theme_dark_onBackground = Color(0xFFE2E2E2)
val md_theme_dark_surface = Color(0xFF121414)
val md_theme_dark_onSurface = Color(0xFFE2E2E2)
val md_theme_dark_surfaceVariant = Color(0xFF333535)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C6D7)
val md_theme_dark_outline = Color(0xFF8B90A0)
val md_theme_dark_inverseOnSurface = Color(0xFF2F3131)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E2)
val md_theme_dark_inversePrimary = Color(0xFF005BC1)

// STITCH Light Theme (Lumina / Premium News)
val md_theme_light_primary = Color(0xFF0058BE)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF2170E4)
val md_theme_light_onPrimaryContainer = Color(0xFFFEFCFF)
val md_theme_light_secondary = Color(0xFF00687A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF57DFFE)
val md_theme_light_onSecondaryContainer = Color(0xFF006172)
val md_theme_light_tertiary = Color(0xFF924700)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFB75B00)
val md_theme_light_onTertiaryContainer = Color(0xFFFFFBFF)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFF9F9FF)
val md_theme_light_onBackground = Color(0xFF141B2B)
val md_theme_light_surface = Color(0xFFF9F9FF)
val md_theme_light_onSurface = Color(0xFF141B2B)
val md_theme_light_surfaceVariant = Color(0xFFDCE2F7)
val md_theme_light_onSurfaceVariant = Color(0xFF424754)
val md_theme_light_outline = Color(0xFF727785)
val md_theme_light_inverseOnSurface = Color(0xFFEDF0FF)
val md_theme_light_inverseSurface = Color(0xFF293040)
val md_theme_light_inversePrimary = Color(0xFFADC6FF)
